version: "3"
services:
  simple_fastapi_on_lambda:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: simple_fastapi_on_lambda-image
    container_name: simple_fastapi_on_lambda-container
    tty: true
    env_file: ../.env # shellスクリプト内でも環境変数として使用するため
